### ISSUE TITLE
Declarative Dependency Disclosure

### ISSUE THREAD

**Issue by ramukima** [micro/os#9]
Is there a way I can declare dependencies for my service on other services in the platform so that my service does not start unless the dependencies are met ?

e.g. My auth service requires a logger service to be available (installed, started, and enabled). My auth service will not run unless the logger service is running. 

Also, is there a way my service dependencies are automatically injected in my service through some metadata. i.e. ready-to-use dependencies corresponding to a meta-namespace for my service, so that I do not have to write the boiler-plate code for discovering the dependencies myself in my service, it just is given to me as long as I have the dependencies declared through some metadata files.

**Comment by asim** [comment]
This is all in the pipeline but not yet implemented. There will be a runtime manager that also handles starting dependencies if they are declared. Dependencies will likely be declared in service at initialisation along with the other options such as name, version, etc. 

So something like:

```
micro.NewService(
  micro.Name("my.service"),
  micro.Version("1.0.1"),
  micro.RuntimeDeps(
    "log.service",
    "auth.service",
  )
)
```

**Comment by ramukima** [comment]
Perfect ! Makes sense.

**Comment by asim** [comment]
Cheers. Closing for now.
